# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#{ config, lib, pkgs, modulesPath, ... }:
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.extraModprobeConfig = ''
    options nvidia_modeset vblank_sem_control=0
  '';
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-amd"
    "nvidia"
    "nvidia-uvm"
  ];
  boot.extraModulePackages = [ ];

  boot.loader.systemd-boot.enable = true;

  boot.kernelPackages = pkgs.linuxPackages_latest;
  #boot.kernelPackages = pkgs.linuxPackages_xanmod_latest;

  # clear /tmp on boot to get a stateless /tmp directory.

  boot.loader.efi.efiSysMountPoint = "/boot";

  boot.tmp.cleanOnBoot = true;

  # Enable binfmt emulation of aarch64-linux, this is required for cross compilation.
  boot.binfmt.emulatedSystems = [
    "aarch64-linux"
    "riscv64-linux"
  ];

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [
      "relatime"
      "mode=755"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/8072ac84-5bee-42f2-861f-555b862148ad";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress-force=zstd:5"
      "noatime"
    ];
  };

  fileSystems."/gnu" = {
    device = "/dev/disk/by-uuid/8072ac84-5bee-42f2-861f-555b862148ad";
    fsType = "btrfs";
    options = [ "subvol=@guix" ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/8072ac84-5bee-42f2-861f-555b862148ad";
    fsType = "btrfs";
    options = [ "subvol=@tmp" ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/8072ac84-5bee-42f2-861f-555b862148ad";
    fsType = "btrfs";
    options = [ "subvol=@swap" ];
  };

  fileSystems."/persistent" = {
    device = "/dev/disk/by-uuid/8072ac84-5bee-42f2-861f-555b862148ad";
    fsType = "btrfs";
    options = [
      "subvol=@persistent"
      "noatime"
      "compress-force=zstd:5"
    ];
    neededForBoot = true;
  };

  fileSystems."/snapshots" = {
    device = "/dev/disk/by-uuid/8072ac84-5bee-42f2-861f-555b862148ad";
    fsType = "btrfs";
    options = [ "subvol=@snapshots" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B6B9-C35A";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp15s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp14s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  services.pulseaudio.enable = false;
  # VR_TODO
  services.nixseparatedebuginfod.enable = true;
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.beta;
}
