# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  pkgs-unstable,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];

  boot.extraModprobeConfig = ''
    options nvidia_modeset vblank_sem_control=0
  '';
  boot.kernelModules = [
    "kvm-intel"
    "nvidia"
    "nvidia-uvm"
  ];
  boot.extraModulePackages = [ ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.efiSysMountPoint = "/boot";

  boot.tmp.cleanOnBoot = true;

  # Enable binfmt emulation of aarch64-linux, this is required for cross compilation.
  boot.binfmt.emulatedSystems = [
    "aarch64-linux"
    "riscv64-linux"
  ];

  # boot.kernelPackages = pkgs-unstable.linuxPackages_latest;
  # boot.kernelPackages = pkgs-unstable.linuxPackages_xanmod_latest;
  # boot.kernelPackages = pkgs-unstable.linuxPackages_zen;
  boot.kernelPackages = pkgs-unstable.linuxPackages_lqx;

  # supported file systems, so we can mount any removable disks with these filesystems
  boot.supportedFilesystems = [
    "ext4"
    "bcachefs"
    "btrfs"
    "xfs"
    "ntfs"
    "fat"
    "vfat"
    "exfat"
  ];

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [
      "relatime"
      "mode=755"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/e2e594be-3bfc-4815-9011-7cc217c9cdf6";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress-force=zstd:5"
      "noatime"
    ];
  };

  fileSystems."/gnu" = {
    device = "/dev/disk/by-uuid/e2e594be-3bfc-4815-9011-7cc217c9cdf6";
    fsType = "btrfs";
    options = [ "subvol=@guix" ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/e2e594be-3bfc-4815-9011-7cc217c9cdf6";
    fsType = "btrfs";
    options = [ "subvol=@tmp" ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/e2e594be-3bfc-4815-9011-7cc217c9cdf6";
    fsType = "btrfs";
    options = [ "subvol=@swap" ];
  };

  fileSystems."/persistent" = {
    device = "/dev/disk/by-uuid/e2e594be-3bfc-4815-9011-7cc217c9cdf6";
    fsType = "btrfs";
    options = [
      "subvol=@persistent"
      "noatime"
      "compress-force=zstd:5"
    ];
    neededForBoot = true;
  };

  fileSystems."/snapshots" = {
    device = "/dev/disk/by-uuid/e2e594be-3bfc-4815-9011-7cc217c9cdf6";
    fsType = "btrfs";
    options = [ "subvol=@snapshots" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B3CD-7DC6";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u4u2c2.useDHCP = lib.mkDefault true;
  # networking.interfaces.Meta.useDHCP = lib.mkDefault true;

  services.pulseaudio.enable = false;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # VR_TODO
  services.nixseparatedebuginfod.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
