# Preservation configuration for additional users on muon machine
# Now with the same complete preservation setup as vitalyr user
let
  # Common complete preservation configuration shared by all users
  # This is identical to vitalyr's configuration
  commonUserPreservation = {
    commonMountOptions = [
      "x-gvfs-hide"
    ];
    directories = [
      # ======================================
      # XDG Directories
      # ======================================

      "Downloads"
      "Music"
      "Pictures"
      "Documents"
      "Videos"

      # ======================================
      # Codes / Work / Playground
      # ======================================
      "projects"
      "tmp"

      # android tools
      "Android"
      # Android Studio
      ".config/Google"
      ".android"

      # google gemini
      ".gemini"

      "Zotero"
      # ".zotero"

      # lean prover
      ".elan"

      # some cache, like clipboard history, sccache
      ".cache"

      # warp-terminal config
      ".config/warp-terminal"

      # gnome configurations
      ".config/dconf"

      ".config/clash-nyanpasu"
      ".config/hiddify"
      ".config/flclash"

      # ======================================
      # Nix / Home Manager Profiles
      # ======================================

      ".local/state/home-manager"
      ".local/state/nix/profiles"
      ".local/share/nix"
      ".cache/nix"
      ".cache/nixpkgs-review"

      # ======================================
      # IDE / Editors
      # ======================================

      # doom-emacs
      ".config/emacs"
      ".local/share/doom"
      ".local/share/emacs"

      # neovim plugins(wakatime & copilot)
      ".wakatime"
      ".config/github-copilot"

      # vscode
      ".vscode"
      ".config/Code"
      ".vscode-insiders"
      ".config/Code - Insiders"

      # godot
      ".config/godot"

      # nvidia profiling tools: nsight-system and nsight-compute
      ".config/NVIDIA Corporation/"
      ".nsightsystems"
      ".nsightcompute"

      # cursor ai editor
      ".cursor"
      ".config/Cursor"

      # zed editor
      ".config/zed"
      ".local/share/zed"

      # ai agents
      ".claude"
      ".gemini"

      # nvim
      ".local/share/nvim"
      ".local/state/nvim"

      # Joplin
      ".config/joplin" # tui client
      ".config/Joplin" # joplin-desktop

      ".local/share/jupyter"

      # qbittorrent
      ".config/qBittorrent"
      ".local/share/qBittorrent"

      # vlc
      ".config/vlc/"
      # mpv
      ".config/mpv/"

      # ======================================
      # Cloud Native
      # ======================================
      {
        # pulumi - infrastructure as code
        directory = ".pulumi";
        mode = "0700";
      }
      {
        directory = ".aws";
        mode = "0700";
      }
      {
        directory = ".aliyun";
        mode = "0700";
      }
      {
        directory = ".config/gcloud";
        mode = "0700";
      }
      {
        directory = ".docker";
        mode = "0700";
      }
      {
        directory = ".kube";
        mode = "0700";
      }
      ".terraform.d/plugin-cache" # terraform's plugin cache

      # ======================================
      # language package managers
      # ======================================
      ".npm" # typsescript/javascript
      "go"
      ".cargo" # rust
      ".rustup"
      ".m2" # java maven
      ".gradle" # java gradle
      ".conda" # python generated by `conda-shell`
      # python pipx
      ".local/pipx"
      ".local/bin"
      # python uv
      ".local/share/uv"
      ".cache/uv"

      # ======================================
      # Security
      # ======================================

      {
        directory = ".gnupg";
        mode = "0700";
      }
      {
        directory = ".ssh";
        mode = "0700";
      }
      {
        directory = ".pki";
        mode = "0700";
      }

      ".local/share/password-store"
      # gnmome keyrings
      ".local/share/keyrings"

      # ======================================
      # Games / Media
      # ======================================

      ".config/blender"
      ".config/LDtk"

      ".local/share/PrismLauncher"

      ".local/share/tiled"
      ".local/share/GOG.com"

      # ======================================
      # Instant Messaging
      # ======================================
      ".config/QQ"

      ".local/share/TelegramDesktop"

      # ======================================
      # Meeting / Remote Desktop
      # ======================================
      ".config/remmina"
      ".config/freerdp"
      ".zoom"

      ".local/share/remmina"

      # ======================================
      # browsers
      # ======================================
      ".mozilla"
      ".config/google-chrome"
      ".cache/google-chrome"
      ".config/chromium"
      ".cache/chromium"

      # ======================================
      # CLI data
      # ======================================
      ".local/share/atuin"
      ".local/share/zoxide"
      ".local/share/direnv"
      ".local/share/k9s"
      ".cache/tealdeer" # tldr

      # ======================================
      # Containers
      # ======================================
      ".local/share/containers"
      ".local/share/flatpak"
      # flatpak app's data
      ".var"

      # ======================================
      # xdg data home & state home
      # Used by:
      #  neovim, flatpak, autin, fcitx5, etc...
      # ======================================
      # XDG_DATA_HOME
      ".local/share"
      # XDG_STATE_HOME
      ".local/state"

      # ======================================
      # Misc
      # ======================================

      # Clash Verge Rev
      ".local/share/io.github.clash-verge-rev.clash-verge-rev"
      ".local/share/clash-verge"

      # Audio
      ".config/pulse"
      ".local/state/wireplumber"

      # Digital Painting
      ".local/share/krita"

      ".config/nushell"
    ];
    files = [
      {
        file = ".wakatime.cfg";
        how = "symlink";
      }
      {
        file = ".config/zoomus.conf";
        how = "symlink";
      }
      {
        file = ".config/zoom.conf";
        how = "symlink";
      }
      {
        file = ".claude.json";
        how = "symlink";
      }
    ];
  };
in
{
  # Persistence directories for additional users
  # Now all users have the same complete preservation setup as vitalyr
  users = {
    xwu = commonUserPreservation;
    cxu = commonUserPreservation;
    zzhou = commonUserPreservation;
  };

  # Systemd tmpfiles configuration for additional users
  tmpfiles =
    let
      userPermission = user: {
        user = user;
        group = "users";
        mode = "0755";
      };
    in
    {
      "/home/xwu/.config".d = userPermission "xwu";
      "/home/xwu/.cache".d = userPermission "xwu";
      "/home/xwu/.local".d = userPermission "xwu";
      "/home/xwu/.local/share".d = userPermission "xwu";
      "/home/xwu/.local/state".d = userPermission "xwu";
      "/home/xwu/.local/state/nix".d = userPermission "xwu";
      "/home/xwu/.terraform.d".d = userPermission "xwu";

      "/home/cxu/.config".d = userPermission "cxu";
      "/home/cxu/.cache".d = userPermission "cxu";
      "/home/cxu/.local".d = userPermission "cxu";
      "/home/cxu/.local/share".d = userPermission "cxu";
      "/home/cxu/.local/state".d = userPermission "cxu";
      "/home/cxu/.local/state/nix".d = userPermission "cxu";
      "/home/cxu/.terraform.d".d = userPermission "cxu";

      "/home/zzhou/.config".d = userPermission "zzhou";
      "/home/zzhou/.cache".d = userPermission "zzhou";
      "/home/zzhou/.local".d = userPermission "zzhou";
      "/home/zzhou/.local/share".d = userPermission "zzhou";
      "/home/zzhou/.local/state".d = userPermission "zzhou";
      "/home/zzhou/.local/state/nix".d = userPermission "zzhou";
      "/home/zzhou/.terraform.d".d = userPermission "zzhou";
    };
}
