# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  source-emacs-lsp-booster = {
    pname = "source-emacs-lsp-booster";
    version = "5f702a2699f306a3958ff1996a2b1a625f0cee0b";
    src = fetchFromGitHub {
      owner = "blahgeek";
      repo = "emacs-lsp-booster";
      rev = "5f702a2699f306a3958ff1996a2b1a625f0cee0b";
      fetchSubmodules = false;
      sha256 = "sha256-R9v+hCma/FfYdR+fvZ0vmtVk4dm+bPBacwV1QCc6X+8=";
    };
    date = "2025-01-07";
  };
  source-emacs-master-igc = {
    pname = "source-emacs-master-igc";
    version = "67161c7fffb92d0ad05a47a303787d7c525a538e";
    src = fetchFromGitHub {
      owner = "emacs-mirror";
      repo = "emacs";
      rev = "67161c7fffb92d0ad05a47a303787d7c525a538e";
      fetchSubmodules = false;
      sha256 = "sha256-ChFlyCBCCxP5WEPLukOqt+9XEmZLwv0h1C7KuXOlrC4=";
    };
    date = "2025-10-05";
  };
}
