# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  source-emacs-lsp-booster = {
    pname = "source-emacs-lsp-booster";
    version = "004bb508c9a2d2877b9145fcccd5437f23a0b669";
    src = fetchFromGitHub {
      owner = "blahgeek";
      repo = "emacs-lsp-booster";
      rev = "004bb508c9a2d2877b9145fcccd5437f23a0b669";
      fetchSubmodules = false;
      sha256 = "sha256-aOkvOyRlkG7gzMy5/x15CMm/voOFOX98QcWVbvfuVLM=";
    };
    date = "2026-04-12";
  };
  source-emacs-master-igc = {
    pname = "source-emacs-master-igc";
    version = "abe63cecccd6e9b67eb567a64b2a157bb460640f";
    src = fetchgit {
      url = "https://github.com/emacs-mirror/emacs.git";
      rev = "abe63cecccd6e9b67eb567a64b2a157bb460640f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Kasm3KYRe2Uncy0fZIAQLQ+wQbV9gEEP6pZdHOUBhvs=";
    };
    date = "2026-05-06";
  };
}
