{
  pkgs,
  config,
  lib,
  myvars,
  ...
}:
with lib;
let
  cfgWayland = config.modules.desktop.wayland;
in
{
  imports = [
    ./base
    ../base

    ./desktop
  ];

  options.modules.desktop = {
    wayland = {
      enable = mkEnableOption "Wayland Display Server";
    };
  };

  config = mkMerge [
    (mkIf cfgWayland.enable {
      ####################################################################
      #  NixOS's Configuration for Wayland based Window Manager
      ####################################################################
      xdg.portal = {
        enable = true;
        wlr.enable = true;
        extraPortals = with pkgs; [
          xdg-desktop-portal-wlr
          xdg-desktop-portal-gnome
        ];
      };

      services = {
        xserver.enable = true;
        displayManager.gdm.enable = true;
        desktopManager.gnome.enable = true;

        # https://wiki.archlinux.org/title/Greetd
        #greetd = {
        #  enable = true;
        #  settings = {
        #    default_session = {
        #      # Wayland Desktop Manager is installed only for user ryan via home-manager!
        #      user = myvars.username;
        #      # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
        #      # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
        #      command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
        #      # command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd $HOME/.wayland-session";  # start wayland session with a TUI login manager
        #    };
        #  };
        #};
      };

      # fix https://github.com/ryan4yin/nix-config/issues/10
      security.pam.services.hyprlock = { };
    })
  ];
}
